---
- name: Malbec filebeak playbook
  hosts: filebeat
  gather_facts: False
  remote_user: ubuntu
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: filebeat }

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install test dependencies.
      apt: name=curl state=present
