---
ansible_os_family: Debian
filebeat_create_config: true

filebeat_prospectors:
  - input_type: log
    paths:
      - "/var/www/log/production.*"

filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "localhost:9200"

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "elk.dereckzenda.com:5044"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/filebeat
filebeat_log_filename: filebeat.log

filebeat_ssl_dir: "
filebeat_ssl_certificate_file: ""
filebeat_ssl_key_file: ""
filebeat_ssl_insecure: ""
